[tool.black]
line_length = 160

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
combine_as_imports = true
line_length = 160
default_section = "THIRDPARTY"

# pylint options can be found here https://www.codeac.io/documentation/pylint-configuration.html
[tool.pylint.BASIC]
docstring-min-length = 10
max-line-length=160
good-names=[
    "i",
    "j",
    "k",
    "ex",
    "Run",
    "_",
    "x",
    "y",
    "fd",
    "f",
    "p",
]

[tool.pylint.DESIGN]
min-public-methods = 0
